### ISSUE TITLE
stack

### ISSUE THREAD

**Issue by flip111** [mightybyte/monad-challenges#27]
I was using haskell platform before, but now i only have stack and i noticed `cabal install` doesn't work anymore, is there any way to make the monad-challenges work with stack?

**Comment by emptyflask** [comment]
I had that same problem. I ran `stack init` to generate the stack.yaml file, but since I had an earlier Stack LTS version, I had to modify it to:

``` yaml
resolver: lts-4.2
packages:
- '.'
extra-deps: []
flags: {}
extra-package-dbs: []
```

Then `stack install`. Also, since I'm using vim for this, I used stack to install ghc-mod and hdevtools.
Use `stack ghci` to load the REPL.
